sudo: required
language: python
  
services:
  - docker

env:
  matrix:
    - wordpress=4.7.4
    - wordpress=4.7.4
    - wordpress=4.6.5
    - wordpress=4.5.8
    - wordpress=4.4.9
    - wordpress=4.3.10
    - wordpress=4.2.14
    - wordpress=4.1.17
    - wordpress=4.0.17
    - wordpress=3.9.18
    - wordpress=3.8.20
    - wordpress=3.7.20

script:
  - bash -x ./test.sh $wordpress $TRAVIS_BUILD_NUMBER
