sudo: required
language:
  
services:
  - docker

env:
  matrix:
    - wordpress=4.7.4
    - wordpress=4.2.1
    - wordpress=3.9.2
    - php=5.5
    - php=5.6

script:
  - echo $wordpress
  - echo $php
#  - ./make.sh 4.7.4 $TRAVIS_BUILD_NUMBER DEV
