sudo: required
language:
  
services:
  - docker

matrix:
  - env:
    - wordpress=4.7.4
    - php=5.5
  - env:
    - wordpress=4.2.1
    - php=5.5
  - env:
    - wordpress=3.9.2
    - php=5.5
  - env:
    - wordpress=4.7.4
    - php=5.6
  - env:
    - wordpress=4.2.1
    - php=5.6
  - env:
    - wordpress=3.9.2
    - php=5.6

script:
  - echo $wordpress
  - echo $php
#  - ./make.sh 4.7.4 $TRAVIS_BUILD_NUMBER DEV
