sudo: required
language: python
  
services:
  - docker

env:
  global:
    - php=5.5

  matrix:
    - wordpress=4.7.4
    - wordpress=4.2.1
    - wordpress=3.9.2

script:
  - echo $wordpress
  - echo $php
  - ./make.sh $wordpress $TRAVIS_BUILD_NUMBER DEV
